version: "3.7"

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn init:prod
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    ports:
      - '10000:10000'

volumes:
  postgres-data:
  redis-data:
